
package cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-25T16:20:21.794+03:00
 * Generated source version: 2.7.18
 * 
 */
public final class TripsService_TripsServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.itis.kpfu.ru/", "TripService");

    private TripsService_TripsServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TripService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TripService ss = new TripService(wsdlURL, SERVICE_NAME);
        TripsService port = ss.getTripsServiceImplPort();  
        
        {
        System.out.println("Invoking findByStatusOrderDate...");
        java.util.List<cxf.Trip> _findByStatusOrderDate__return = port.findByStatusOrderDate();
        System.out.println("findByStatusOrderDate.result=" + _findByStatusOrderDate__return);


        }
        {
        System.out.println("Invoking findAllOrderDate...");
        java.util.List<cxf.Trip> _findAllOrderDate__return = port.findAllOrderDate();
        System.out.println("findAllOrderDate.result=" + _findAllOrderDate__return);


        }
        {
        System.out.println("Invoking findById...");
        java.lang.Long _findById_arg0 = null;
        cxf.Trip _findById__return = port.findById(_findById_arg0);
        System.out.println("findById.result=" + _findById__return);


        }
        {
        System.out.println("Invoking lastEndsTripsForMonth...");
        cxf.User _lastEndsTripsForMonth_arg0 = new cxf.User();
        java.util.List<cxf.Trip> _lastEndsTripsForMonth__return = port.lastEndsTripsForMonth(_lastEndsTripsForMonth_arg0);
        System.out.println("lastEndsTripsForMonth.result=" + _lastEndsTripsForMonth__return);


        }
        {
        System.out.println("Invoking addTrip...");
        cxf.Trip _addTrip_arg0 = new cxf.Trip();
        cxf.Trip _addTrip__return = port.addTrip(_addTrip_arg0);
        System.out.println("addTrip.result=" + _addTrip__return);


        }
        {
        System.out.println("Invoking update...");
        cxf.Trip _update_arg0 = new cxf.Trip();
        port.update(_update_arg0);


        }
        {
        System.out.println("Invoking lastTrips...");
        java.util.List<cxf.Trip> _lastTrips__return = port.lastTrips();
        System.out.println("lastTrips.result=" + _lastTrips__return);


        }
        {
        System.out.println("Invoking findBySearch...");
        java.lang.String _findBySearch_arg0 = "";
        java.lang.String _findBySearch_arg1 = "";
        java.util.List<cxf.Trip> _findBySearch__return = port.findBySearch(_findBySearch_arg0, _findBySearch_arg1);
        System.out.println("findBySearch.result=" + _findBySearch__return);


        }
        {
        System.out.println("Invoking findAll...");
        java.util.List<cxf.Trip> _findAll__return = port.findAll();
        System.out.println("findAll.result=" + _findAll__return);


        }

        System.exit(0);
    }

}
