package cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-25T16:20:21.903+03:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "TripService", 
                  wsdlLocation = "file:/D:/ITIS/dz_labs/4 term/testWS/src/main/java/cxf/tripService.wsdl",
                  targetNamespace = "http://impl.service.itis.kpfu.ru/") 
public class TripService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.itis.kpfu.ru/", "TripService");
    public final static QName TripsServiceImplPort = new QName("http://impl.service.itis.kpfu.ru/", "TripsServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/ITIS/dz_labs/4 term/testWS/src/main/java/cxf/tripService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TripService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/ITIS/dz_labs/4 term/testWS/src/main/java/cxf/tripService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TripService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TripService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TripService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TripService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TripService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TripService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TripsService
     */
    @WebEndpoint(name = "TripsServiceImplPort")
    public TripsService getTripsServiceImplPort() {
        return super.getPort(TripsServiceImplPort, TripsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TripsService
     */
    @WebEndpoint(name = "TripsServiceImplPort")
    public TripsService getTripsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TripsServiceImplPort, TripsService.class, features);
    }

}
